channels:
- conda-forge
dependencies:
- python=3.9.10
- pip<=22.1.2
- pip:
  - mlflow
  - category-encoders==2.5.0
  - cloudpickle==2.1.0
  - psutil==5.9.1
  - scikit-learn==1.1.2
  - typing-extensions==4.3.0
name: mlflow-env
