access_control:
  account_name: samleuwrnd
  container_name: ml-dummy-data
  connection_string: DefaultEndpointsProtocol=https;AccountName=samleuwrnd;AccountKey=ioynEf2DCUDQdgUnf9V/OkYhYjlddzcJxw/BlhavKrpKvmh9weXahmINYg93OEP2CuvH2y7ejcyW+ASt9/HOPg==;EndpointSuffix=core.windows.net

base:
  clientname: clientname_data
  project: big_mart_sales
  random_state: 42
  target_col: Item_Outlet_Sales 

data_source:
  az_source: azure://samleuwrnd/poc/data/  # dummy azure storage replace with actual

load_data:
  raw_dataset_csv: package/data/raw_files/

split_data:
  train_path: package/data/interim_files/train.csv
  test_path: package/data/interim_files/test.csv
  test_size: 0.2

processed_data:
  train_path: package/data/interim_files/train.csv
  test_path: package/data/interim_files/test.csv



estimators:
  random_forest_regressor:
    params:
      n_estimators: 
        - 10
        - 50
        - 100
        - 130 
      criterion: 
        - gini
        - entropy
      max_depth: 
        - 2
        - 4
        - 6
        - 8
        - 10
        - 12
      max_features: 
        - auto
        - log2
      min_samples_leaf:
        - 2
        - 4
        
  linear_regression:
  support_vector_regression:
    params:
      kernel:
        - linear
        - poly
        - rbf
        - precomputed
      degree:
        - 2
        - 4
        - 5
      C:
        - 1
        - 10
        - 100
        - 1000  

model_dir: models

reports:
  params: package/reports/params.json
  scores: package/reports/scores.json

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: poc_sales_prediction
  run_name: random_forest
  registered_model_name: random_forest_model
  remote_server_uri: http://localhost:1234

webapp_model_dir: package/prediction_service/model/model.joblib # for testing purpose only in real case VO UI will be used